version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  snyk-test:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run: npm install snyk
      - run: npx snyk auth $SNYK_TOKEN
      - run:
          name: Run Snyk Test
          command: npx snyk test

  zap-test:
    docker:
      - image: ghcr.io/zaproxy/zaproxy:stable
    steps:
      - checkout
      - run:
          name: Start OWASP ZAP API Security Scan
          command: |
            zap-cli quick-scan http://localhost:3000/api/auth/signin
            zap-cli quick-scan http://localhost:3000/api/auth/session
            zap-cli quick-scan http://localhost:3000/api/auth/signout

workflows:
  version: 2
  security-workflow:
    jobs:
      - build
      - snyk-test:
          requires:
            - build
      - zap-test:
          requires:
            - build
