version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:20.11.1
    working_directory: ~/project
  zap-executor:
    docker:
      - image: ghcr.io/zaproxy/zaproxy:stable
    working_directory: ~/project
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build the app
          command: npm run build
      - run:
          name: Start the app in background (dev)
          command: npm run start -- --hostname 0.0.0.0 &
      - run:
          name: Wait for app to start
          command: sleep 30
      - run:
          name: Check if Node.js process is running
          command: ps aux | grep node
      - run:
          name: Verbose curl to check app (ignore cert)
          command: curl -vk https://localhost:3000/
  snyk-test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install Snyk
          command: npm install snyk
      - run:
          name: Authenticate Snyk
          command: npx snyk auth $SNYK_TOKEN
      - run:
          name: Run Snyk Test
          command: npx snyk test
  zap-test:
    executor: zap-executor
    steps:
      - checkout
      - run:
          name: Start OWASP ZAP API Security Scan
          command: |
            zap.sh -cmd -quickurl https://localhost:3000/api/auth/signin -quickprogress -quickout /tmp/zap_signin_report.html
            zap.sh -cmd -quickurl https://localhost:3000/api/auth/session -quickprogress -quickout /tmp/zap_session_report.html
            zap.sh -cmd -quickurl https://localhost:3000/api/auth/signout -quickprogress -quickout /tmp/zap_signout_report.html
      - store_artifacts:
          path: /tmp/zap_signin_report.html
          destination: zap_signin_report.html
      - store_artifacts:
          path: /tmp/zap_session_report.html
          destination: zap_session_report.html
      - store_artifacts:
          path: /tmp/zap_signout_report.html
          destination: zap_signout_report.html
workflows:
  version: 2
  security-workflow:
    jobs:
      - build
      - snyk-test:
          requires:
            - build
      - zap-test:
          requires:
            - build
