version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  snyk-test:
  docker:
    - image: cimg/node:20.11.1
  steps:
    - checkout
    - run: npm install snyk
    - run: npx snyk auth $SNYK_TOKEN
    - run:
        name: Run Snyk Test
        command: npx snyk test

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - snyk-test:
          requires:
            - build